name: Upsert Secret
description: Adds or updates a secret in a .env file
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.secret_name }}
    - ${{ inputs.secret_value }}
    - ${{ inputs.secret_file_path }}
    - ${{ inputs.additional_args }}

inputs:
  secret_name:
    description: The name of the secret to add or update
    required: true
  secret_value:
    description: The value of the secret
    required: true
  secret_file_path:
    description: Path to the .env file
    required: true
  additional_args:
    description: Additional arguments to be passed to sops command, for example specifying the keys for encryption and decryption.
    required: false
